# General 
Device      : 'cuda'
num_epochs  : 3
seed        : 42

Dataset :
  samples_per_test    : 32768
  Total_test          : 24
  test_Duration       : 2

model :
  # model         Maybe adding dropout in LSTM is good
  input_horizon       : 400
  # model-LSTM
  LSTM_outFeature     : 200
  LSTM_NumLayer       : 3
  LSTM_hidden_size    : 100
  # model-CNN
  CNN_inChannel       : 1
  CNN_outChannel      : 10
  CNN_outFeature      : 100


CWT :
  Scales              : 51
  wavelet_lis         : ['mexh','morl','gaus1','cmor1-1.0']   # Define the wavelet and scales
  wavelet             : 1                        # You can choose other wavelet functions as well
  Coefficient_Real    : True