# General 
Device      : 'cuda'
num_epochs  : 1
seed        : 42

Dataset :
  samples_per_test    : 32768
  Total_test          : 24
  test_Duration       : 2

model :
  # model         Maybe adding dropout in LSTM is good
  input_horizon       : 200
  # model-LSTM
  LSTM_outFeature     : 60
  LSTM_NumLayer       : 1
  LSTM_hidden_size    : 50
  # model-CNN
  CNN_inChannel       : 1
  CNN_outChannel      : 10
  CNN_outFeature      : 80

CWT :
  Scales              : 100 # 50
  wavelet_lis         : ['mexh','morl','gaus1','cmor1-1.0']   # Define the wavelet and scales
  wavelet             : 2                       # You can choose other wavelet functions as well
  Coefficient_Real    : True

loss:
  label_smoothing     : 0.3

optimizer:
  learning_rate       : 0.0001
  momentum            : 0.9
  weight_decay        : 0.001
